apiVersion: v1
kind: Service
metadata:
  labels:
    app_name: {{ .Values.server.name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.server.name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
      app_name: {{ .Values.server.name }}