{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.alertmanager.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.alertmanager.name }}
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}