{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app_name: {{ .Values.blackbox.name }}
    app_version: {{ .Values.blackbox.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.blackbox.name }}
{{- end }}