apiVersion: v1
kind: Service
metadata:
  labels:
    app_name: {{ .Values.blackbox.name }}
    app_version: {{ .Values.blackbox.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.blackbox.name }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9115
  selector:
    app_name: {{ .Values.blackbox.name }}