apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kubernetes-controller-manager
  labels:
    app_name: {{ .Values.server.name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    component: kube-controller-manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 10252
    targetPort: 10252
    protocol: TCP